### ISSUE TITLE
Unsafe for concurrency

### ISSUE THREAD

**Issue by tech10** [firstrow/tcp_server#18]
Currently, race testing fails. This library is not concurrent safe, and probably should be.

**Comment by firstrow** [comment]
The test itself was not implemented properly. Please see commit https://github.com/firstrow/tcp_server/commit/035a34bfcefa33e357153e404fbf2d06496551b7

Thanks. 👍

**Comment by tech10** [comment]
I can still see several examples of this library being used concurrently on the same server or client object. Currently, this will produce race conditions. While I can agree that the users code should be safe for concurrency, the libraries behind the users code should also be safe. The commit referenced only fixes the race test, but I think the library itself should be safe for concurrent operation. If this is modified to be concurrent safe, the tests should intentionally attempt to produce race conditions to try and test the concurrent safety of the library. Since this is a server library, I think it's a good assumption to make that concurrent operations will occur.

**Comment by firstrow** [comment]
This makes a lot of sense.
