### ISSUE TITLE
Handle

### ISSUE THREAD

**Issue by ghost** [firstrow/tcp_server#2]
Hello,

why are you using channel (s.joins <- conn) instead of just call goroutine immediately ( go client.listen())?

Cheers!

**Comment by firstrow** [comment]
Hello. Because on this step(line: (92) client is not created.
Basically, this can be refactored.

**Comment by ghost** [comment]
Sorry, but question is about architecture, why use channels? Look at this example https://github.com/beyondns/nsk/blob/master/core/nsk.go

why not just go handler(conn) ?

**Comment by firstrow** [comment]
no significant reason. just personal choice. I think this should be refactored.
