### ISSUE TITLE
May be add

### ISSUE THREAD

**Issue by truebest** [firstrow/tcp_server#3]
func (c \* Client) GetLocalAddress() net.Addr{
    return c.conn.LocalAddr()
}

func (c \* Client) GetRemoteAddress() net.Addr{
    return c.conn.RemoteAddr()
}

for get local remote address?

**Comment by firstrow** [comment]
I think better would be:

``` go
func (c * Client) GetConn() net.Conn {
  return c.conn
}
```

and usage:

``` go
c.GetConn().GetRemoteAddress()
```

**Comment by firstrow** [comment]
add Conn() method
