### ISSUE TITLE
Message broadcasting

### ISSUE THREAD

**Issue by dzmitrys-dev** [firstrow/tcp_server#9]
Hello! Nice library, but is there a method for message broadcasting to all clients?

**Comment by firstrow** [comment]
Hi. No, there is no such method. I try to keep this library simple. So broadcasting should be implemented on app level. for example

``` go
clients := []*tcp_server.Client
server.OnNewClient(func(c *tcp_server.Client) {
    clients = append(clients, c)
})
```
